### ISSUE TITLE
侧边栏菜单bug

### ISSUE THREAD

**Issue by sealye09** [d3george/slash-admin#104]
二级菜单激活并且菜单状态为收缩时，展开菜单，上方会有节点没消失，应该是子菜单的popup没消失。
猜测是rc-menu的openKeys用flushSync更新的问题。
![图片](https://github.com/user-attachments/assets/bb7505db-452a-4428-9483-7d2b50ec8784)

**Comment by d3george** [comment]
这个问题 我一直没找到解决办法😂

**Comment by sealye09** [comment]
> 这个问题 我一直没找到解决办法😂

其实 tab 的动画也跟主体内容区域不同步
