### ISSUE TITLE
[bug] antd flex布局 需要 版本升级下  "antd": "^5.9.3" 改成  "antd": "^5.22.4",

### ISSUE THREAD

**Issue by yanjinbin** [d3george/slash-admin#109]
https://ant.design/components/flex-cn 
5.10.0版本后支持

**Comment by d3george** [comment]
<img width="812" alt="image" src="https://github.com/user-attachments/assets/e8a704c2-5024-4293-84bd-97e18ed894ce">

^5.9.3 并不是固定为 5.9.3

**Comment by yanjinbin** [comment]
> <img alt="image" width="812" src="https://private-user-images.githubusercontent.com/143698843/393887755-e8a704c2-5024-4293-84bd-97e18ed894ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NjMxNjksIm5iZiI6MTczMzg2Mjg2OSwicGF0aCI6Ii8xNDM2OTg4NDMvMzkzODg3NzU1LWU4YTcwNGMyLTUwMjQtNDI5My04NGJkLTk3ZTE4ZWQ4OTRjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQyMDM0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTQ1M2JlNzMwNjcwZWMyNGZmZmYyNDY0MWRmMjZiYWQzY2UxNDhmYzA4Mjg4Y2M0NDJkYmQ4NDlhYzBlODhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ljIdCtimARuS3scU_D--RgY55_9lbjlnfZNc4A4kzZo">
> ^5.9.3 并不是固定为 5.9.3

semver语意下 是次修版本可以一直升级 问题是我执行pnpm install ,run 之后 确实有这个问题?  可能我之前有老版本 5.9.x 就不重新拉取了?

**Comment by d3george** [comment]
删除 pnpm-lock.yml 重新执行 pnpm install
