### ISSUE TITLE
Tailwind Color部分的样式不生效

### ISSUE THREAD

**Issue by lvvlan** [d3george/slash-admin#114]
在项目中使用Tailwind Color部分的样式时不生效，只有使用下图中配置的这些样式才能生效，这是什么原因呢？只能使用项目中的配置Color不能使用Tailwind 提供的Color预定义样式吗？

![image](https://github.com/user-attachments/assets/173f4ec7-2c8a-49a0-ac1c-879db78f45e5)

非常感谢作者提供的这个模板，很棒很棒！

**Comment by sealye09** [comment]
这个配置会覆盖默认的配置，需要extend才行。
具体可以看：https://tailwindcss.com/docs/theme#extending-the-default-theme

**Comment by d3george** [comment]
关于主题这块 目前在重构中 color部分没使用extend的原因是为了限制随意使用颜色 所有颜色都应出自颜色预设
