### ISSUE TITLE
如何控制子目录的权限？

### ISSUE THREAD

**Issue by lvvlan** [d3george/slash-admin#116]
例如dashboard路由下，角色1可以看到所有的子目录，角色2只能看见dashboard/workbench，看了权限的文档似乎没有这样的设置，但是看线上的demo，权限-系统-角色这里面似乎可以编辑用户的权限，但好像不生效，看了下代码好像没有这块的逻辑？

**Comment by d3george** [comment]
权限是登陆时接口返回的

**Comment by lvvlan** [comment]
我知道是接口返回的，但我看返回的接口格式并不能控制子目录的权限，我看代码里似乎没有控制子目录的逻辑，有可能是我没找到？
