### ISSUE TITLE
怎么不验证登录

### ISSUE THREAD

**Issue by dxl-enter** [d3george/slash-admin#117]
不需要任何权限直接进入首页，需要改那些文件呢？

**Comment by d3george** [comment]
<img width="665" alt="image" src="https://github.com/user-attachments/assets/76652845-953a-4427-bf52-0a6463d433b8" />

**Comment by dxl-enter** [comment]
不需要验证token，直接进入首页

**Comment by uxff** [comment]
注释后需要用return getRoutesFromModules();代替。否则无返回值。
