### ISSUE TITLE
hideMenu之后 无法跳转到对应页面

### ISSUE THREAD

**Issue by Kutius** [d3george/slash-admin#2]
某些情况：menu中不需要显示，但是可以跳转到对应页面
现在好像没办法实现这种需求

**Comment by Kutius** [comment]
另外想请教一下如何设置menu的顺序，比如需要给某个menu设成最后面，order改成100也无效果

**Comment by d3george** [comment]
> 某些情况：menu中不需要显示，但是可以跳转到对应页面 现在好像没办法实现这种需求
fixed at : https://github.com/d3george/slash-admin/commit/cc08e055855705beda94bc4936d7c12052523668

**Comment by d3george** [comment]
> 另外想请教一下如何设置menu的顺序，比如需要给某个menu设成最后面，order改成100也无效果

fixed at: https://github.com/d3george/slash-admin/commit/7e3631f9a791491dd1fd630ddb611e42e340dc7c
