### ISSUE TITLE
支持docker部署

### ISSUE THREAD

**Issue by xinmans** [d3george/slash-admin#21]
https://github.com/xinmans/slash-admin.git

合并下，给个PR提交权限

**Comment by d3george** [comment]
直接提交pr就行，我测试下没问题就合并了

**Comment by xinmans** [comment]
> 直接提交pr就行，我测试下没问题就合并了

done

**Comment by d3george** [comment]
我优化了一下 271cf37c04034e4dc4ef4cd4fc515a8528e297d4
