### ISSUE TITLE
[Bug] 收缩菜单时会收缩所有展开的菜单，无论几级

### ISSUE THREAD

**Issue by laojianzi** [d3george/slash-admin#24]
首先点赞一下 UI，看起来还是挺舒服的

---

说一下这个收缩菜单的行为，这或许不是一个 bug，但从用户体验角度来说，这个行为比较影响使用体验。

![ezgif-2-9a479b240d](https://github.com/d3george/slash-admin/assets/42930263/2a499cf3-c89a-46c3-890d-5a5baf625c6f)

**Comment by peijunlei** [comment]
直接setOpenKeys(keys)就好了吧

**Comment by lucyanddarlin** [comment]
`onOpenChange` 函数中直接 `setOpenKeys(keys)`; 或者 `<Menu />` 取消 `openKey ` 的配置。目前还不清楚作者是特定这样编写的逻辑还是说这是一个 BUG。

**Comment by d3george** [comment]
目前就是这么设计的
