### ISSUE TITLE
使用动态路由后，是不是就不需要在routes下定义静态路由？

### ISSUE THREAD

**Issue by nianhua99** [d3george/slash-admin#25]
RT，路由的定义都由后端传过来是吗

**Comment by d3george** [comment]
https://github.com/d3george/slash-admin/blob/bbf013e0d45f9f5c9459ac1869d984462809b5da/src/_mock/_user.js#L27
 权限数据是mock后端返回的，会根据这份mock的权限数据转换成路由配置

**Comment by nianhua99** [comment]
了解了！
