### ISSUE TITLE
导航栏的菜单配置需要文档说明

### ISSUE THREAD

**Issue by changan29** [d3george/slash-admin#27]
不清楚如何增删默认的导航菜单， 定制化配置需要文档说明

**Comment by moweiwei** [comment]
const pages = import.meta.glob('/src/pages/**/*.tsx');
文件路由，文件名结构就是路由结构

**Comment by wdskdl** [comment]
为什么我修改了order之后顺序还是没有变呢

**Comment by d3george** [comment]
> 为什么我修改了order之后顺序还是没有变呢

你在哪里修改的order
