### ISSUE TITLE
📌 Welcome to join the Discord channel to discuss everything about slash-admin.

### ISSUE THREAD

**Issue by d3george** [d3george/slash-admin#30]
[Discord](https://discord.gg/fXemAXVNDa)

**Comment by d3george** [comment]
[Document](https://docs-admin.slashspaces.com/)

**Comment by imxw** [comment]
![image](https://github.com/d3george/slash-admin/assets/16207029/1e5a4f27-047a-4699-84b4-fffe67e16009)
邀请过期了
