### ISSUE TITLE
用了下 很不错 。不过关于路由权限这块可以帮完善下基础的使用文档嘛

### ISSUE THREAD

**Issue by eternallycyf** [d3george/slash-admin#44]
十分感谢 ! 用了下 很不错  🎉 🎉 🎉 
- 我是重新搭建的 用了最新的vite5 unocss等依赖
## [仓库地址](https://github.com/eternallycyf/ims-admin/tree/main)

有两个现在不好处理的
- 动态路由现在只会生成一个tab  => use/:id  不同的id应该生成不同的tab才对 这个好像不太好改
- 可以帮完善下基础的使用文档嘛 关于路由配置 权限 这块

发现了几个小问题 有项目要用 我自己的先修复了
## 1.tabs不能滑动 最好还是能达到图二的效果
<img width="1433" alt="截屏2024-04-06 00 42 04" src="https://github.com/d3george/slash-admin/assets/63464198/1bd9f395-e85b-46c8-8fbc-bea94fbb4412">
<img width="1134" alt="截屏2024-04-06 00 44 00" src="https://github.com/d3george/slash-admin/assets/63464198/2a1eb411-652b-4b28-b1df-5ae02c47f24d">

## 2.主题色好像使用起来不太方便 
  - 我在vite中注入了所有antd的主题色token自定义了8个全局变量 到全局 使用vscode插件达到less文件有提示
  - 自定义了8个全局变量 通过less变量 unocss html-var antd的useToken都可以使用

## 3.动态路由好像有点问题 点击跳转到动态路由 然后点一下自己的tab标题 路径就会变成这样 只有第一次正常的
<img width="486" alt="截屏2024-04-06 00 55 04" src="https://github.com/d3george/slash-admin/assets/63464198/29c5c87e-bcdf-4a4e-aca5-f18db7f5fc78">

- 应该要 保存 params search state 参数。增加了一个配置用于动态路由设置标题

<img width="353" alt="截屏2024-04-06 00 56 02" src="https://github.com/d3george/slash-admin/assets/63464198/16057d3f-edeb-40e9-abf5-88280e9a64dd">

## 5.这里需要做一下空的处理 如果本地没文件会触发ErrorBoundary 定位bug也不太好定位 我把404页面 || 了一下

<img width="793" alt="截屏2024-04-06 01 01 53" src="https://github.com/d3george/slash-admin/assets/63464198/f3749681-0415-493b-9e41-6d06131a6090">

**Comment by d3george** [comment]
有问题欢迎提pr修复，另外我们有个discord频道可以讨论问题，有需要可以加入

文档近期打算开始弄了

**Comment by d3george** [comment]
你好，今天处理了下你提到的几个问题：
问题1： 这个是可以滚动的，你可以仔细试试
问题2和4： 可以在你自己的项目里添加这个功能
问题3和5：感谢提出这两个问题，已经修复，

**Comment by eternallycyf** [comment]
好的 谢谢👌🏻
