### ISSUE TITLE
第一次进入一级路由会重新渲染 只有部署的环境会出现 本地没事

### ISSUE THREAD

**Issue by eternallycyf** [d3george/slash-admin#48]
只有第一次进去就会这样 复现直接清除浏览器所有记录即可
我这样改了之后就好了 
![324222892-8d9c4549-336e-4809-9108-0e1120cd876f](https://github.com/d3george/slash-admin/assets/63464198/716ed5f6-4159-4089-bd2e-c9c50c1e2656)

<img width="815" alt="截屏2024-04-21 13 43 42" src="https://github.com/d3george/slash-admin/assets/63464198/ba525168-01c6-47da-907e-f96b2c7395ac">

**Comment by d3george** [comment]
fixed
