### ISSUE TITLE
有没有感觉左侧的栏目展开时有卡顿

### ISSUE THREAD

**Issue by FishOrBear** [d3george/slash-admin#50]
ui做的不错，就是antd这个动画感觉很不流畅，我现在用pad pro m1访问

**Comment by d3george** [comment]
这个还没找到原因，或者 你可以尝试去解决😀

**Comment by hhhhhhhhhhhg** [comment]
+1， 访问官方示例的时候，也感觉左侧菜单栏动画不太流程
我是 PC端 Edge

**Comment by labike** [comment]
+2,看起来不自然

**Comment by labike** [comment]
+2,看起来不自然

**Comment by labike** [comment]
@d3george 简单方式: 左侧菜单栏加个过度动画应该可以好点
```
<div
      className="flex h-full flex-col"
      style={{
        width: collapsed ? NAV_COLLAPSED_WIDTH : NAV_WIDTH,
        borderRight: `1px dashed ${Color(colorBorder).alpha(0.6).toString()}`,
  
          transition: 'width 0.15s',
        
      }}
    >
```
` transition: 'width 0.15s'`

**Comment by xianb** [comment]
+1，而且我发现，只要打开后台，cpu占用就100% @d3george

**Comment by d3george** [comment]
没遇到过

**Comment by d3george** [comment]
我对菜单相关代码进行了优化，我个人感觉现在不卡顿了，大家觉得还卡顿吗

**Comment by xianb** [comment]
我测试下来，有两个地方占用cpu非常高。
第一个地方，使用framer-motion库的动画，cpu基本100%，比如首页顶部的设置按钮，我把动画关掉后，cpu使用正常。
第二个地方，使用了antd库带动效的组件，cpu的使用率就会升高，比如loading的时候加载的Spin组件，由于cpu基本到100%，大概需要2-3秒才能加载完，去掉Spin组件，基本1秒就加载完。另一个，连续点击菜单(展开/合并)，观察cpu，也会飙的很高。我猜菜单动效的卡顿跟cpu使用率太高有关系。
测试电脑：mac/intel

**Comment by mindsfsdfwe** [comment]
![image](https://github.com/d3george/slash-admin/assets/149565440/ca78957d-27b7-4b1d-b8c7-709568eb13ec)
![image](https://github.com/d3george/slash-admin/assets/149565440/36fde1c3-0728-41e4-8b9f-67b357c0f7c3)
  
这个菜单的加载 好像轮训多次加载了

**Comment by mindsfsdfwe** [comment]
> 行吧，既然这么多人反馈，打算重写菜单这块了，不用antd的menu组件了，自己写

应该不是这个组件的问题， 我控制台输出一下 这个菜单的加载 多次被调用

**Comment by mindsfsdfwe** [comment]
> 行吧，既然这么多人反馈，打算重写菜单这块了，不用antd的menu组件了，自己写

应该不是这个组件的问题， 我控制台输出一下 这个菜单的加载 多次被调用 @d3george

**Comment by d3george** [comment]
是的，这块正在改

**Comment by d3george** [comment]
> > 行吧，既然这么多人反馈，打算重写菜单这块了，不用antd的menu组件了，自己写
> 
> 应该不是这个组件的问题， 我控制台输出一下 这个菜单的加载 多次被调用 @d3george

整个项目有很多地方用到了`usePermissionRoutes`， 当然会打印很多此了

**Comment by ryangopher** [comment]
![1720974293536](https://github.com/user-attachments/assets/33810ced-090a-4bfe-a742-5c8eedeef78f)
这块改成useMemo流畅了一些，M1 Pro

**Comment by d3george** [comment]
> ![1720974293536](https://private-user-images.githubusercontent.com/8108560/348556681-33810ced-090a-4bfe-a742-5c8eedeef78f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTEzNTgsIm5iZiI6MTcyMTAxMTA1OCwicGF0aCI6Ii84MTA4NTYwLzM0ODU1NjY4MS0zMzgxMGNlZC0wOTBhLTRiZmUtYTc0Mi01YzhlZWRlZWY3OGYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMDIzNzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjg3N2NiMGI0Y2FmYzVlODkyNjg4NjU3YmUyNjBmNDVjNWE3NDQwYzRlNTVlMzMxYWYyYjZlNTNmOGNmNTMwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zaQeBfkzhHeuryYDU9UFUwH34pxgFLdSmlbRu3Z_GhU) <img alt="image" width="716" src="https://private-user-images.githubusercontent.com/8108560/348558148-960c5edc-a264-4994-8f4c-1cca072b64f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTEzNTgsIm5iZiI6MTcyMTAxMTA1OCwicGF0aCI6Ii84MTA4NTYwLzM0ODU1ODE0OC05NjBjNWVkYy1hMjY0LTQ5OTQtOGY0Yy0xY2NhMDcyYjY0ZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMDIzNzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTUwYWYyNjVlODg3MjZjYjNiNmQwNDdlZGE2YTZlYmExNmJmNzBlNWJlMDE5OWEzZjlhMmVkMjZiZjY0YTNhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yr8w0-BbSvQtD03NtqHMIm99HL0_6U1ze6bOgWzTarE"> M1 Pro：这块改成useMemo流畅了一些，再加上antd menu主题配置动画快一些，没有感觉卡顿了

可以提交个pr

**Comment by ryangopher** [comment]
PR已提交 @d3george
