### ISSUE TITLE
项目中存在2个，vite-env.d.ts 文件

### ISSUE THREAD

**Issue by ntscshen** [d3george/slash-admin#54]
vite-env.d.ts
```javascript
/// <reference types="vite/client" />
```

**vite/client** 是为了增强在使用TS开发项目时，Vite特定功能(环境变量和热更新)的开发体验。

我在项目目录结构中发现了两组 `vite-env.d.ts` 文件。从具体内容看，现有代码的根目录下存在的 `vite-env.d.ts`文件是**src**目录下`vite-env.d.ts`文件的超集。

我不太清楚是否有特定的项目配置，需要在 src 目录中再次显式声明类型引用。
合理猜测它可能存在一定冗余。我只做了简单的测试，将src目录中的 `vite-env.d.ts` 删除后，在用到 `import.meta.env` 的地方类型提示和类型检查都是健康的。但是Vite官网文档中它们给的案例中确实将当前文件写在了src文件夹中。

从简化项目结构看，如果没有额外的必要性，通常保留根目录下的版本是合适。
我不太清楚必要性有多强，我只是提出一些疑惑和可能的优化建议。

感谢查看~

**Comment by d3george** [comment]
可以建个pr 处理 我来合并

**Comment by d3george** [comment]
我们又一个discord讨论群，可以加一下，有什么问题能得到及时响应
