### ISSUE TITLE
build 报错

### ISSUE THREAD

**Issue by arch3754** [d3george/slash-admin#60]
<img width="1358" alt="image" src="https://github.com/d3george/slash-admin/assets/16916249/cfa89f8e-1c3f-4cfd-8be6-5529ddb04b16">

**Comment by d3george** [comment]
能提供下环境吗

**Comment by arch3754** [comment]
mac os 14.5
node v22.2.0
npm 10.7.0

**Comment by d3george** [comment]
无法复现

**Comment by d3george** [comment]
https://github.com/d3george/slash-admin/commit/3991bcdcbfb50381689254539dbd749b73ece797#diff-bc379658e10e82ec9724dd8bf7ff1237b53b259fe4ea1b1945cc3fad1829de5a
