### ISSUE TITLE
路由缓存

### ISSUE THREAD

**Issue by qiuzixu** [d3george/slash-admin#64]
大佬你这个路由缓存是怎么实现的 我看了一下遍代码怎么没发现

**Comment by d3george** [comment]
我们有个discord群，可以进群讨论

**Comment by qiuzixu** [comment]
好的

**Comment by qiuzixu** [comment]
> 我们有个discord群，可以进群讨论

大佬，群在哪里加我怎么没看到

**Comment by qiuzixu** [comment]
> > 我们有个discord群，可以进群讨论
> 
> 大佬，群在哪里加我怎么没看到

找到了e

**Comment by WillemHia** [comment]
在哪里加群

**Comment by d3george** [comment]
<img width="395" alt="image" src="https://github.com/user-attachments/assets/f767ee35-9436-4cb6-acac-dbc2b955cc27">
