### ISSUE TITLE
Theme Fix: Error Messages Not Following Dark Theme

### ISSUE THREAD

**Issue by joaoflaviosantos** [d3george/slash-admin#72]
Hello @d3george,

Firstly, I want to commend you on the excellent work with this template; it has been incredibly valuable to me!

I need your assistance to address a visual bug where error messages do not adhere to the dark theme:

![image](https://github.com/d3george/slash-admin/assets/80658056/72191ab5-a028-4741-8aa9-084eac8b13dd)

There are two instances where this occurs, as listed below, and they do not adjust to the dark theme when it is applied:

src\components\upload\utils.ts
```tsx
  if (!isJpgOrPng) {
    message.error('You can only upload JPG/PNG file!');
  }
```
src\api\apiClient.ts
```tsx
    const errMsg = response?.data?.message || message || t('sys.api.errorMessage');
    Message.error(errMsg);
```

Thank you in advance for your help!

Best regards,

João Flavio Santos

**Comment by d3george** [comment]
Thank you for your report. I will fix it in the next version

**Comment by joaoflaviosantos** [comment]
hello again @d3george!

Maybe it will help:

[Ant Design Issue](https://github.com/ant-design/ant-design/issues/40576#issuecomment-1431077191)

**Comment by d3george** [comment]
Static methods cannot consume Context. Please use hooks first.

**Comment by d3george** [comment]
I have used sonner to replace the message, alert, notification and other components of antd

<img width="2323" alt="image" src="https://github.com/user-attachments/assets/dd345e4c-45af-4f16-958e-19a8ae3f4e8d">
