### ISSUE TITLE
Support for defaultProps will be removed from memo components in a future major release. 

### ISSUE THREAD

**Issue by huangxinbo** [d3george/slash-admin#73]
在使用 react-beautiful-dnd 的地方，在开发环境下提示 warning，比如 multi-tabs 组件
chunk-ONWOSD36.js?v=ebdad770:521 Warning: Connect(Droppable): Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.

**Comment by d3george** [comment]
我把react版本从18.3回退到18.2之后，这个问题就消失了
