### ISSUE TITLE
How to add or remove menu item ?

### ISSUE THREAD

**Issue by NuzzGunners** [d3george/slash-admin#74]

**Comment by d3george** [comment]
https://github.com/d3george/slash-admin/blob/main/src/_mock/assets.js

**Comment by NuzzGunners** [comment]
I try edit. assets.js  but web page is not change.
<img width="1680" alt="Screenshot 2567-07-10 at 10 38 46" src="https://github.com/d3george/slash-admin/assets/26136454/79ea1d11-8d78-4f99-814b-8e7350812e42">
<img width="1680" alt="Screenshot 2567-07-10 at 10 38 25" src="https://github.com/d3george/slash-admin/assets/26136454/950502d0-e549-4190-a5d5-52fd37fcd18d">

**Comment by d3george** [comment]
logout and login

**Comment by NuzzGunners** [comment]
thank you

**Comment by d3george** [comment]
we have a Discord channel, you can join it, then we can talk more easily
