### ISSUE TITLE
react.development.js:1357 Uncaught TypeError: ctor is not a function

### ISSUE THREAD

**Issue by dhanraj-chaintech** [d3george/slash-admin#77]
![image](https://github.com/user-attachments/assets/424bf65b-f3ea-4e3d-98e8-850b0b4bb8da)

**Comment by dhanraj-chaintech** [comment]
when I am connecting node js backend application and retrivating route data from my backend it shows error

**Comment by DHANRAJCHOUDHARY244** [comment]
I waste my lot of time but I can't able to fix this bugs.

**Comment by d3george** [comment]
How to reproduce this problem❓

**Comment by dhanraj-chaintech** [comment]
I solved this by writing my own permissions logic.  This  repo is great solution for all cms project.

**Comment by d3george** [comment]
> I solved this by writing my own permissions logic. This repo is great solution for all cms project. Thank buddy.

for your problem, perhaps the deconstruction of the routing object you returned does not match the slash admin

last, thank you for your affirmation！
