### ISSUE TITLE
水平菜单空间不足子菜单标题展示不全

### ISSUE THREAD

**Issue by ryangopher** [d3george/slash-admin#78]
<img width="1016" alt="image" src="https://github.com/user-attachments/assets/e601a1dc-19a4-4a5e-8256-293caae08b57">
我看antd官网示例空间不足时菜单标题展示是全的，没有找到是哪个地方的样式影响到了

**Comment by ryangopher** [comment]
找到了，在useRouteToMenuFn中
```
<div
	className={`inline-flex w-full items-center ${
	  themeLayout === ThemeLayout.Horizontal ? 'justify-start' : 'justify-between'
	} `}
>
	<div className="">{t(label)}</div>
	{suffix}
</div>
```

**Comment by joaoflaviosantos** [comment]
> 找到了，在useRouteToMenuFn中
> 
> ```
> <div
> 	className={`inline-flex w-full items-center ${
> 	  themeLayout === ThemeLayout.Horizontal ? 'justify-start' : 'justify-between'
> 	} `}
> >
> 	<div className="">{t(label)}</div>
> 	{suffix}
> </div>
> ```

Hello @ryangopher!

Did you manage to resolve this? Could you share the solution?

**Comment by d3george** [comment]
If you can solve it, you can submit a PR

**Comment by ryangopher** [comment]
@joaoflaviosantos I used the menuItem.label
```
        menuItem.label = (
              <div className="flex items-center">
                {typeof icon === 'string' &&
                  (icon.startsWith('ic') ? (
                    <SvgIcon icon={icon} size={24} className="ant-menu-item-icon" />
                  ) : (
                    <Iconify icon={icon} size={24} className="ant-menu-item-icon" />
                  ))}
                <div className="ml-2">{t(label)}</div>
                {suffix}
              </div>
            );
```

**Comment by ryangopher** [comment]
> If you can solve it, you can submit a PR

Great repo. I’m newer for React😁

**Comment by joaoflaviosantos** [comment]
> @joaoflaviosantos I use the menuItem.label
> 
> ```
>         menuItem.label = (
>               <div className="flex items-center">
>                 {typeof icon === 'string' &&
>                   (icon.startsWith('ic') ? (
>                     <SvgIcon icon={icon} size={24} className="ant-menu-item-icon" />
>                   ) : (
>                     <Iconify icon={icon} size={24} className="ant-menu-item-icon" />
>                   ))}
>                 <div className="ml-2">{t(label)}</div>
>                 {suffix}
>               </div>
>             );
> ```

Hello again @ryangopher!

Thank you for your response, but it's still not quite right. This change altered the original template too much.

The adjustment I've made for now is to use 'w-full' only in the vertical version:
```typescript
            menuItem.label = (
              <div
                className={`inline-flex items-center ${
                  themeLayout === ThemeLayout.Horizontal
                    ? 'justify-start'
                    : 'w-full justify-between'
                } `}
              >
                <div className="">
                  {t(label)}
                </div>
                {suffix}
              </div>
            );
```

With this adjustment alone, it's almost correct, as shown below:

![image](https://github.com/user-attachments/assets/885994ab-5894-4e19-bc26-6d8c47ba8cee)

@d3george, do you have any other suggestions?

**Comment by d3george** [comment]
https://github.com/d3george/slash-admin/commit/6c04aeab0d8205b20204b597b2d204937d0955fd#diff-bc379658e10e82ec9724dd8bf7ff1237b53b259fe4ea1b1945cc3fad1829de5aL30

**Comment by d3george** [comment]
<img width="1267" alt="image" src="https://github.com/user-attachments/assets/c5d8a691-b244-4903-9975-740a336dcbbb">
