### ISSUE TITLE
Sorry, Page error occurred!

### ISSUE THREAD

**Issue by chenxin9482** [d3george/slash-admin#82]
操作流程：
git clone xxx(项目git地址
pnpm install
pnpm dev
boom! 无法启动
![image](https://github.com/user-attachments/assets/9a55c234-703d-4411-a102-db4d8136092d)

**Comment by d3george** [comment]
请问你是什么浏览器

**Comment by chenxin9482** [comment]
edge
node版本18.18

**Comment by d3george** [comment]
我这边按你的环境是正常的，无法复现

**Comment by chenxin9482** [comment]
是 不知道为啥 清楚缓存的确可以

**Comment by chenxin9482** [comment]
另外我想问下怎么添加菜单啊 我在route配置了页面不显示欸

**Comment by d3george** [comment]
路由是从后端返回的
