### ISSUE TITLE
打包后，http-server运行dist报错

### ISSUE THREAD

**Issue by luckycui-cyber** [d3george/slash-admin#85]
项目运行打包命令后，http-server运行dist预览，点击登录报错，信息如下：
![20240929-172548](https://github.com/user-attachments/assets/5259c4c3-ce9b-4a2a-9a23-6ffb60584e88)

**Comment by d3george** [comment]
可以提供更详细的信息吗

**Comment by luckycui-cyber** [comment]
> 可以提供更详细的信息吗

按照文档操作流程，build打包成功后，使用http-server运行dist文件，浏览器访问界面，点击登录直接出现如下报错：
Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Request': Request body is already used
    at Vve.respondWith (index-d7b3fac3.js:386:44994)
    at Object.onResponse (index-d7b3fac3.js:386:52313)
    at a (index-d7b3fac3.js:386:35316)
    at wve (index-d7b3fac3.js:386:36696)
    at async l.onRequest (index-d7b3fac3.js:386:52225)
不知道更详细的信息是指什么？

**Comment by d3george** [comment]
1. 是用的npm yarn 还是 pnpm 打包
2. 浏览器是什么

**Comment by luckycui-cyber** [comment]
> 1. pnpm



> 1. 是用的npm yarn 还是 pnpm 打包
> 2. 浏览器是什么

用的pnpm打包
浏览器是chrome
这个报错会和模拟接口文件有关系吗？pnpm preview方式访问是没问题的。http-server访问才会有这个问题

**Comment by d3george** [comment]
我试了 chrome  firfox edge 三个浏览器 都没问题

**Comment by luckycui-cyber** [comment]
> 我试了 chrome firfox edge 三个浏览器 都没问题

太奇怪啦，那我更新下chrome版本，在重新打包下试试吧。。。。

**Comment by d3george** [comment]
你在 discord 群吗，在的话我们在群里讨论

**Comment by luckycui-cyber** [comment]
> 你在 discord 群吗，在的话我们在群里讨论
> 
> 你查看下你的pnpm-lock.yml
> 
> <img alt="image" width="701" src="https://private-user-images.githubusercontent.com/143698843/371920360-5da92d50-48d3-49d3-8390-861e593c50b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NjIwNDEsIm5iZiI6MTcyNzY2MTc0MSwicGF0aCI6Ii8xNDM2OTg4NDMvMzcxOTIwMzYwLTVkYTkyZDUwLTQ4ZDMtNDlkMy04MzkwLTg2MWU1OTNjNTBiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwMjAyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDQ4MTJlOWU2YTM5ODhmNGJiODc0YjVkMmM2MzVmZTVjNGQ0YmQ4MDk3MzQ2OTM5MWJmNjc2MzdiYjUxMWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jF2vvusmNkBIMW4jdR59V0tZPjuwagapIirH7B7KRi0">
> msw的版本是什么
可以告诉我群号吗，我申请加入
查看版本如下：
msw:
        specifier: ^2.2.14
        version: 2.4.5(typescript@5.6.2)
