### ISSUE TITLE
请问如何关闭路由缓存？

### ISSUE THREAD

**Issue by Shimada666** [d3george/slash-admin#86]
作者您好！非常感谢您开源的这个作品，页面很好看。
我是一名 vue 开发者，最近在学习 react，遇到一个问题，我发现我页面切换时数据不会重新加载，判断是和页面被缓存了有关。我希望每次切换时数据能够重新加载。我一路定位到 multi-tab 的 Tabs，但我不知道如何关闭这个缓存的功能。我期望是每次切换页面都能重新获取数据、加载页面。
请问如何实现呢，期待回复

**Comment by d3george** [comment]
![Uploading image.png…]()

**Comment by d3george** [comment]
我们有个Discord 频道，可以加下，后续有问题直接在群里问，我能及时看到
