### ISSUE TITLE
建议区分版本

### ISSUE THREAD

**Issue by songtang0** [d3george/slash-admin#92]
楼主最近是不是比较忙，我看文档和代码已经不吻合了。这个如何去掉权限校验不用mock的路由而只用前端自己定义的呢，现在不是根据pages自动注册路由的

**Comment by d3george** [comment]
<img width="1075" alt="Arc 2024-10-24 11 09 50" src="https://github.com/user-attachments/assets/406e5f9e-bab3-4d30-9a01-b473e62ba87c">

https://github.com/d3george/slash-admin/blob/7d17ec15d6cda979b3553602505f01ecebd62171/src/router/hooks/use-permission-routes.tsx#L34-L50

**Comment by d3george** [comment]
有个Discord 群， 可以加下，有问题在群里 我能即使吹拂

**Comment by songtang0** [comment]
我试出来了，找了半天。嘻嘻，谢谢楼主大佬，可能是公司网络问题，Discord失败一直，等回家我再加一下试试

**Comment by d3george** [comment]
Discord 需要科学上网
