### ISSUE TITLE
可以做个侧边栏深色功能吗

### ISSUE THREAD

**Issue by huajun-912** [d3george/slash-admin#94]
可以做个侧边栏深色功能吗

**Comment by d3george** [comment]
这个可以有

**Comment by huajun-912** [comment]
左侧菜单怎么可以单个展开神

**Comment by d3george** [comment]
没明白你什么意思

**Comment by huajun-912** [comment]
就是权限菜单现在每个点开了都是展开状态，能不能可以设置只展开一个

**Comment by huajun-912** [comment]
![微信图片_20241103071316](https://github.com/user-attachments/assets/19ac5bd6-f852-4764-aa06-152e2a49fbc6)
就这个

**Comment by d3george** [comment]
已实现
