### ISSUE TITLE
手机浏览器兼容问题

### ISSUE THREAD

**Issue by huajun-912** [d3george/slash-admin#97]
手机浏览器打开，竖屏状态，左侧权限菜单无法上下滑动，底部的菜单看不到

**Comment by d3george** [comment]
我们有一个Discord群，可以加一下， 有问题能及时响应

**Comment by d3george** [comment]
网站右上角

**Comment by d3george** [comment]
https://discord.gg/pdRu3Tuk

**Comment by huajun-912** [comment]
哈哈，这个网站我就没打开过，公司vpn，家里网络，手机网络，都没打开过发自我的手机-------- 原始邮件 --------发件人： kevin ***@***.***>日期： 2024年11月8日周五 18:57收件人： d3george/slash-admin ***@***.***>抄送： huajun-912 ***@***.***>, Author ***@***.***>主    题： Re: [d3george/slash-admin] 手机浏览器兼容问题 (Issue #97)
https://discord.gg/pdRu3Tuk

**Comment by d3george** [comment]
学会科学上网

**Comment by huajun-912** [comment]
好的，听你的，去公司再试试发自我的手机-------- 原始邮件 --------发件人： kevin ***@***.***>日期： 2024年11月8日周五 19:06收件人： d3george/slash-admin ***@***.***>抄送： huajun-912 ***@***.***>, Author ***@***.***>主    题： Re: [d3george/slash-admin] 手机浏览器兼容问题 (Issue #97)
学会科学上网
