### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by cxqeric** [d3george/slash-admin#98]
报错如下，无论是用`yarn`还是`pnpm`，均报错，是跟什么版本有关系吗？
![image](https://github.com/user-attachments/assets/a3b79611-0727-4be1-a291-ec210430b338)
或者这样的错误
![image](https://github.com/user-attachments/assets/2a0463ee-640e-4618-8adf-c7edb3564da1)

**Comment by d3george** [comment]
找到问题了吗

**Comment by d3george** [comment]
👌 我之前排查过 在我手上的几台设备上都无法复现
